ROOT = ../../../
BINS = testcov.exe testsubbag.exe testseq.exe
#BINS = testsubbag.exe
EXTLIBS = $(ROOT)util/common/util.a
TESTS = testcov.exe testsubbag.exe
#LIBS = linal.a
#OBJS = gauss.o


include $(ROOT)all.inc
MPICC=$(CPP)
-include deps.inc

