ROOT = ../../
BINS = rna.exe rnabnb.exe rnapar.exe polarbnb.exe
OBJS = rnagen.o
LIBS = rna.a
EXTLIBS = $(ROOT)util/aclib/mpiaclib.a $(ROOT)util/common/util.a $(ROOT)problems/optlib/optlib.a $(ROOT)kernel/bnblib/bnblib.a

include $(ROOT)all.inc
-include deps.inc
