ROOT = ../../../../../
BINS = runpolybc.exe 
#EXTLIBS = $(ROOT)util/aclib/mpiaclib.a $(ROOT)util/common/util.a $(ROOT)problems/optlib/optlib.a $(ROOT)kernel/bnblib/bnblib.a 
EXTLIBS =  $(ROOT)util/common/util.a $(ROOT)problems/optlib/optlib.a 
				
include $(ROOT)all.inc
-include deps.inc