ROOT = ../../../
BINS = multid.exe lipzic.exe lipzicmsheur.exe test.lipg.exe 
EXTLIBS = $(ROOT)util/aclib/mpiaclib.a $(ROOT)util/common/util.a $(ROOT)problems/optlib/optlib.a $(ROOT)kernel/bnblib/bnblib.a 
TESTS = test.lipg.exe
				
include $(ROOT)all.inc
include $(ROOT)mpi.inc
-include deps.inc
