ROOT = ../../


#BINS = bnbsolver.exe bnbterm.exe bnbss.exe bnbgrid.exe
BINS = bnbterm.exe bnbss.exe bnbgrid.exe
EXTLIBS = $(ROOT)util/aclib/mpiaclib.a $(ROOT)util/common/util.a $(ROOT)problems/optlib/optlib.a $(ROOT)kernel/bnblib/bnblib.a $(ROOT)/problems/crypto/crypto.a $(ROOT)problems/ampl/asl/asl/amplsolver.a


include $(ROOT)all.inc
#EXTRA_INC = $(ROOT)problems/knapsack/
-include deps.inc
