# DO NOT CHANGE BELOW THIS LINE

all dep clean indent tests::
	cd multiopt && $(MAKE) $@ && cd .. &&\
	cd multicov && $(MAKE) $@ && cd .. &&\
	cd multipar && $(MAKE) $@ && cd .. &&\
	cd examples && $(MAKE) $@ && cd .. 

