ROOT = ../../../
BINS =  test.polylip.exe 
EXTLIBS = $(ROOT)util/common/util.a $(ROOT)problems/optlib/optlib.a $(ROOT)kernel/bnblib/bnblib.a 
TESTS =  test.polylip.exe

include $(ROOT)all.inc
-include deps.inc

