ROOT = ../../../../
BINS = main.exe test.sq.exe
EXTLIBS = $(ROOT)util/aclib/mpiaclib.a $(ROOT)util/common/util.a $(ROOT)problems/optlib/optlib.a $(ROOT)kernel/bnblib/bnblib.a 
TESTS = test.sq.exe

include $(ROOT)all.inc
-include deps.inc
