ROOT = ../../
LIBS = optlib.a 
EXTLIBS = $(ROOT)util/common/util.a
OBJS = lbfgs.o lmbfgs.o cbfgs.o
BINS = opttest.exe testboxlo.exe test.polyobj.exe  test.polyobj1.exe tstlocmincheck.exe
TESTS = opttest.exe testboxlo.exe test.polyobj.exe test.polyobj1.exe tstlocmincheck.exe

include $(ROOT)/all.inc
-include deps.inc

