ROOT = ../../../
BINS =  locsearch.exe morsesearch.exe smolec.exe lipmolec.exe
EXTLIBS =  $(ROOT)util/common/util.a $(ROOT)problems/optlib/optlib.a $(ROOT)kernel/bnblib/bnblib.a

include $(ROOT)all.inc
MPICC=$(CPP)
-include deps.inc
