ROOT = ../../../
BINS = testhsutils.exe testhsresolver.exe seqsolver.exe heursolver.exe seqsolver2.exe seqsolver3.exe
TESTS = testhsutils.exe testhsresolver.exe
EXTLIBS = $(ROOT)util/common/util.a $(ROOT)libjson/libjson.a


include $(ROOT)all.inc
MPICC=$(CPP)
-include deps.inc

