all dep clean indent tests::
	cd mcnlp && $(MAKE) $@ && cd .. &&\
	cd mbh && $(MAKE) $@ && cd .. &&\
	cd cuts && $(MAKE) $@ && cd .. &&\
	cd bnc && $(MAKE) $@ && cd .. &&\
	cd poly && $(MAKE) $@ && cd .. &&\
	cd testproblems && $(MAKE) $@ && cd ..
	