all dep clean indent tests::
	cd sq && $(MAKE) $@ && cd .. &&\
	cd g4 && $(MAKE) $@ && cd .. &&\
	cd g6 && $(MAKE) $@ && cd .. &&\
	cd g11 && $(MAKE) $@ && cd .. &&\
	cd vessel && $(MAKE) $@ && cd .. &&\
	cd lambda && $(MAKE) $@ 

