ROOT = ../../../
BINS = testbncsolver.exe testbnceigen.exe
#EXTLIBS = $(ROOT)util/aclib/mpiaclib.a $(ROOT)util/common/util.a $(ROOT)problems/optlib/optlib.a $(ROOT)kernel/bnblib/bnblib.a 
EXTLIBS =  $(ROOT)util/common/util.a $(ROOT)problems/optlib/optlib.a 
TESTS = testbncsolver.exe
				
include $(ROOT)all.inc
-include deps.inc