ROOT = ../../
BINS = inttest.exe  infinitest.exe randomtest.exe polartest.exe qubictest.exe vecsegtest.exe 
LIBS = util.a
OBJS = soch.o util.o mmregistry.o memmanager.o bnblog.o bnbdebug.o


include $(ROOT)all.inc
-include deps.inc

