ROOT = ../../../
BINS = unconspolysolver.exe test.polysupp.exe
#EXTLIBS = $(ROOT)util/aclib/mpiaclib.a $(ROOT)util/common/util.a $(ROOT)problems/optlib/optlib.a $(ROOT)kernel/bnblib/bnblib.a 
EXTLIBS =  $(ROOT)util/common/util.a $(ROOT)problems/optlib/optlib.a 
TESTS = test.polysupp.exe
				
include $(ROOT)all.inc
-include deps.inc