ROOT = ../../../
BINS =  testseq.exe ssumseq.exe
TESTS = testseq.exe
EXTLIBS = $(ROOT)util/common/util.a
#LIBS = linal.a
#OBJS = gauss.o


include $(ROOT)all.inc
#include $(ROOT)mpi.inc
-include deps.inc

