ROOT = ../../../
BINS =  molec.exe
EXTLIBS =  $(ROOT)util/aclib/mpiaclib.a $(ROOT)util/common/util.a $(ROOT)problems/optlib/optlib.a $(ROOT)kernel/bnblib/bnblib.a

include $(ROOT)all.inc
include $(ROOT)mpi.inc
-include deps.inc
