ROOT = ../../../
BINS = testpoint.exe testmultimc.exe testlocsearch.exe testmultiser.exe
TESTS = testmultiser.exe
EXTLIBS = $(ROOT)util/common/util.a
#LIBS = linal.a
#OBJS = gauss.o


include $(ROOT)all.inc
MPICC=$(CPP)
-include deps.inc

