ROOT = ../../
BINS = test.monom.exe test.polynom.exe test.pars.exe
EXTLIBS = $(ROOT)util/common/util.a 
TESTS = test.monom.exe test.polynom.exe  test.pars.exe

include $(ROOT)all.inc
-include deps.inc

